version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1

# only trigger in master branch
workflows:
  all:
    jobs:
      - build:
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install dependencies
          command: |
            npm run frontend:install
            npm run backend:install
      - run:
          name: Build
          command: |
            npm run frontend:build
            npm run backend:build
      - run:
          name: Deploy UI
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
